import type { Service } from "@radiance/types";

export const services: Service[] = [
  // Thermal & Bathing
  {
    id: "sauna-session",
    name: "Sauna Session",
    slug: "sauna-session",
    category: "thermal-bathing",
    description: "Experience the traditional Finnish sauna, heated to the perfect temperature for deep relaxation and detoxification. Our wood-lined sauna room provides an authentic experience that helps cleanse your body of toxins, improve circulation, and relieve muscle tension.",
    shortDescription: "Traditional Finnish sauna for deep relaxation and detoxification.",
    benefits: [
      "Detoxifies the body through sweating",
      "Improves blood circulation",
      "Relieves muscle tension and pain",
      "Promotes better sleep",
      "Cleanses and rejuvenates skin",
    ],
    duration: [30, 45],
    price: { 30: 10000, 45: 14000 },
    images: ["/images/services/sauna-1.jpg", "/images/services/sauna-2.jpg"],
    thumbnail: "/images/services/sauna-thumb.jpg",
    rating: 4.8,
    reviewCount: 89,
    addOns: ["aromatherapy", "cold-plunge"],
    isPopular: true,
    preparation: "Please hydrate well before your session. Avoid heavy meals 1-2 hours before.",
    whatToExpect: "You'll be provided with towels and slippers. The sauna is maintained at 80-100°C.",
  },
  {
    id: "hammam-experience",
    name: "Hammam Experience",
    slug: "hammam-experience",
    category: "thermal-bathing",
    description: "Immerse yourself in the centuries-old tradition of the Turkish bath. Our Hammam experience includes steam bathing, exfoliation with a traditional kessa glove, and a rejuvenating black soap treatment.",
    shortDescription: "Traditional Turkish bath with steam, exfoliation, and black soap treatment.",
    benefits: [
      "Deep cleanses and exfoliates skin",
      "Opens pores and removes impurities",
      "Improves skin texture and glow",
      "Relaxes muscles and joints",
      "Provides stress relief",
    ],
    duration: [45, 60],
    price: { 45: 15000, 60: 20000 },
    images: ["/images/services/hammam-1.jpg", "/images/services/hammam-2.jpg"],
    thumbnail: "/images/services/hammam-thumb.jpg",
    rating: 4.9,
    reviewCount: 67,
    addOns: ["aromatherapy", "body-mask"],
    isPopular: true,
    preparation: "Come with clean skin. Remove all jewelry before the treatment.",
    whatToExpect: "The experience includes steam room, body scrub, and relaxation in our rest area.",
  },
  {
    id: "steam-bath",
    name: "Steam Bath",
    slug: "steam-bath",
    category: "thermal-bathing",
    description: "Our eucalyptus-infused steam bath provides a gentle yet effective way to relax and cleanse. The warm, moist air opens your pores, clears your sinuses, and leaves you feeling refreshed and revitalized.",
    shortDescription: "Eucalyptus-infused steam bath for gentle cleansing and relaxation.",
    benefits: [
      "Clears respiratory system",
      "Opens pores for deep cleansing",
      "Hydrates and softens skin",
      "Relieves congestion",
      "Promotes relaxation",
    ],
    duration: [30, 45],
    price: { 30: 10000, 45: 14000 },
    images: ["/images/services/steam-1.jpg"],
    thumbnail: "/images/services/steam-thumb.jpg",
    rating: 4.7,
    reviewCount: 54,
    addOns: ["aromatherapy"],
    preparation: "Stay hydrated. Best enjoyed before a massage treatment.",
    whatToExpect: "Our steam room is maintained at 40-45°C with 100% humidity.",
  },

  // Massage & Therapy
  {
    id: "swedish-massage",
    name: "Swedish Massage",
    slug: "swedish-massage",
    category: "massage-therapy",
    description: "Our signature Swedish massage uses long, flowing strokes combined with kneading and circular movements to promote total relaxation. This classic technique improves circulation, eases muscle tension, and creates a sense of overall well-being.",
    shortDescription: "Classic relaxation massage with long, flowing strokes for total well-being.",
    benefits: [
      "Promotes deep relaxation",
      "Improves blood circulation",
      "Reduces muscle tension",
      "Decreases stress hormones",
      "Improves flexibility",
    ],
    duration: [60, 90],
    price: { 60: 25000, 90: 35000 },
    images: ["/images/services/swedish-1.jpg", "/images/services/swedish-2.jpg"],
    thumbnail: "/images/services/swedish-thumb.jpg",
    rating: 4.9,
    reviewCount: 156,
    addOns: ["aromatherapy", "hot-stones", "scalp-massage"],
    isPopular: true,
    preparation: "Arrive 10 minutes early to relax. Communicate any areas of concern to your therapist.",
    whatToExpect: "You'll be draped for privacy. Pressure can be adjusted to your preference.",
  },
  {
    id: "deep-tissue-massage",
    name: "Deep Tissue Massage",
    slug: "deep-tissue-massage",
    category: "massage-therapy",
    description: "Targeted deep tissue work focuses on the deeper layers of muscle and connective tissue. Using firm pressure and slow strokes, this massage is ideal for chronic pain, muscle knots, and areas of tension.",
    shortDescription: "Intensive massage targeting deep muscle layers for chronic tension relief.",
    benefits: [
      "Relieves chronic muscle pain",
      "Breaks down scar tissue",
      "Improves posture",
      "Increases range of motion",
      "Reduces inflammation",
    ],
    duration: [60, 90],
    price: { 60: 30000, 90: 42000 },
    images: ["/images/services/deep-tissue-1.jpg"],
    thumbnail: "/images/services/deep-tissue-thumb.jpg",
    rating: 4.8,
    reviewCount: 98,
    addOns: ["hot-stones", "cupping"],
    isPopular: true,
    preparation: "Drink plenty of water before and after. Inform therapist of any injuries.",
    whatToExpect: "Expect firm pressure. Some areas may feel tender during treatment.",
  },
  {
    id: "hot-stone-massage",
    name: "Hot Stone Massage",
    slug: "hot-stone-massage",
    category: "massage-therapy",
    description: "Smooth, heated basalt stones are placed on key points of the body and used as massage tools. The penetrating heat relaxes muscles deeply, allowing the therapist to work more effectively.",
    shortDescription: "Heated basalt stones combined with massage for deep muscle relaxation.",
    benefits: [
      "Deep muscle relaxation",
      "Improves blood flow",
      "Reduces stress and anxiety",
      "Eases muscle stiffness",
      "Promotes better sleep",
    ],
    duration: [75, 90],
    price: { 75: 35000, 90: 45000 },
    images: ["/images/services/hot-stone-1.jpg"],
    thumbnail: "/images/services/hot-stone-thumb.jpg",
    rating: 4.9,
    reviewCount: 72,
    addOns: ["aromatherapy", "scalp-massage"],
    preparation: "Avoid caffeine before treatment. Wear loose clothing.",
    whatToExpect: "Stones are heated to 50-55°C. The warmth penetrates deeply into muscles.",
  },
  {
    id: "aromatherapy-massage",
    name: "Aromatherapy Massage",
    slug: "aromatherapy-massage",
    category: "massage-therapy",
    description: "This sensory journey combines the power of touch with therapeutic essential oils. Choose from our selection of oil blends designed for relaxation, energy, or balance.",
    shortDescription: "Sensory massage experience with therapeutic essential oils of your choice.",
    benefits: [
      "Enhances mood and emotions",
      "Promotes deep relaxation",
      "Reduces anxiety",
      "Improves sleep quality",
      "Nourishes skin",
    ],
    duration: [60, 90],
    price: { 60: 28000, 90: 40000 },
    images: ["/images/services/aromatherapy-1.jpg"],
    thumbnail: "/images/services/aromatherapy-thumb.jpg",
    rating: 4.8,
    reviewCount: 84,
    addOns: ["scalp-massage"],
    preparation: "Let us know if you have any allergies or sensitivities to scents.",
    whatToExpect: "You'll choose your essential oil blend before the treatment begins.",
  },
  {
    id: "couples-massage",
    name: "Couples Massage",
    slug: "couples-massage",
    category: "massage-therapy",
    description: "Share a relaxing experience with your partner in our private couples suite. Two therapists work simultaneously, allowing you to enjoy the benefits of massage together.",
    shortDescription: "Side-by-side massage experience for two in our private couples suite.",
    benefits: [
      "Shared relaxation experience",
      "Strengthens connection",
      "Creates lasting memories",
      "Individual attention from two therapists",
      "Private romantic atmosphere",
    ],
    duration: [60, 90],
    price: { 60: 50000, 90: 70000 },
    images: ["/images/services/couples-1.jpg"],
    thumbnail: "/images/services/couples-thumb.jpg",
    rating: 5.0,
    reviewCount: 45,
    addOns: ["champagne", "aromatherapy", "hot-stones"],
    isPopular: true,
    preparation: "Arrive 15 minutes early to settle in together.",
    whatToExpect: "Private suite with two massage tables. Choose your preferred massage style.",
  },

  // Beauty & Grooming
  {
    id: "signature-facial",
    name: "Signature Facial",
    slug: "signature-facial",
    category: "beauty-grooming",
    description: "Our signature facial is customized to your skin type and concerns. Includes deep cleansing, exfoliation, extraction, mask, and hydration for glowing, healthy skin.",
    shortDescription: "Customized facial treatment for your specific skin type and concerns.",
    benefits: [
      "Deep cleanses pores",
      "Improves skin texture",
      "Hydrates and nourishes",
      "Reduces signs of aging",
      "Creates healthy glow",
    ],
    duration: [60, 90],
    price: { 60: 20000, 90: 30000 },
    images: ["/images/services/facial-1.jpg"],
    thumbnail: "/images/services/facial-thumb.jpg",
    rating: 4.8,
    reviewCount: 92,
    addOns: ["eye-treatment", "lip-treatment"],
    isPopular: true,
    preparation: "Come with clean skin. Avoid exfoliating 24 hours before.",
    whatToExpect: "Your esthetician will analyze your skin and customize the treatment.",
  },
  {
    id: "manicure-pedicure",
    name: "Manicure & Pedicure",
    slug: "manicure-pedicure",
    category: "beauty-grooming",
    description: "Complete nail care for hands and feet including shaping, cuticle care, exfoliation, massage, and polish application. Choose from our premium polish collection.",
    shortDescription: "Complete nail care for hands and feet with polish of your choice.",
    benefits: [
      "Well-groomed nails",
      "Soft, smooth skin",
      "Improved circulation",
      "Relaxation",
      "Professional finish",
    ],
    duration: [60, 90],
    price: { 60: 15000, 90: 22000 },
    images: ["/images/services/mani-pedi-1.jpg"],
    thumbnail: "/images/services/mani-pedi-thumb.jpg",
    rating: 4.7,
    reviewCount: 68,
    addOns: ["gel-polish", "nail-art", "paraffin-treatment"],
    preparation: "Remove any existing polish before your appointment.",
    whatToExpect: "Includes soak, shaping, cuticle care, scrub, massage, and polish.",
  },
  {
    id: "hair-styling",
    name: "Hair Styling",
    slug: "hair-styling",
    category: "beauty-grooming",
    description: "Professional hair styling services including wash, cut, blow dry, and styling. Our expert stylists will help you achieve your desired look.",
    shortDescription: "Professional hair wash, cut, and styling by expert stylists.",
    benefits: [
      "Fresh, polished look",
      "Professional expertise",
      "Personalized consultation",
      "Quality products",
      "Styling tips",
    ],
    duration: [45, 60, 90],
    price: { 45: 8000, 60: 12000, 90: 18000 },
    images: ["/images/services/hair-1.jpg"],
    thumbnail: "/images/services/hair-thumb.jpg",
    rating: 4.6,
    reviewCount: 54,
    addOns: ["deep-conditioning", "scalp-treatment"],
    preparation: "Bring reference photos of styles you like.",
    whatToExpect: "Consultation, wash, cut, blow dry, and styling included.",
  },

  // Fitness
  {
    id: "gym-access",
    name: "Gym Access",
    slug: "gym-access",
    category: "fitness",
    description: "Access our state-of-the-art gym facility equipped with modern cardio machines, free weights, resistance equipment, and more. Perfect for your daily workout routine.",
    shortDescription: "Full access to our state-of-the-art gym and fitness equipment.",
    benefits: [
      "Modern equipment",
      "Climate controlled",
      "Clean facilities",
      "Locker rooms included",
      "Towel service",
    ],
    duration: [60, 120],
    price: { 60: 5000, 120: 8000 },
    images: ["/images/services/gym-1.jpg"],
    thumbnail: "/images/services/gym-thumb.jpg",
    rating: 4.5,
    reviewCount: 42,
    addOns: ["personal-training"],
    preparation: "Bring appropriate workout attire and shoes.",
    whatToExpect: "Full access to all gym equipment. Towels and water provided.",
  },
  {
    id: "aerobics-class",
    name: "Aerobics Class",
    slug: "aerobics-class",
    category: "fitness",
    description: "High-energy group fitness classes led by certified instructors. Join us for fun, effective workouts that improve cardiovascular health and burn calories.",
    shortDescription: "Fun, high-energy group fitness classes for all levels.",
    benefits: [
      "Cardiovascular health",
      "Calorie burning",
      "Group motivation",
      "Fun workout",
      "Improved coordination",
    ],
    duration: [45, 60],
    price: { 45: 5000, 60: 6000 },
    images: ["/images/services/aerobics-1.jpg"],
    thumbnail: "/images/services/aerobics-thumb.jpg",
    rating: 4.7,
    reviewCount: 38,
    addOns: [],
    preparation: "Wear comfortable workout clothes. Bring water.",
    whatToExpect: "Instructor-led class with warm-up, main workout, and cool-down.",
  },
];

export function getServiceById(id: string): Service | undefined {
  return services.find((s) => s.id === id);
}

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export function getServicesByCategory(categoryId: string): Service[] {
  return services.filter((s) => s.category === categoryId);
}

export function getPopularServices(): Service[] {
  return services.filter((s) => s.isPopular);
}

export function getFeaturedServices(limit: number = 6): Service[] {
  return services.slice(0, limit);
}
