spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:radiance_wellness}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:0000}
  jpa:
    show-sql: true

logging:
  level:
    com.zaidom.radiancewellness: DEBUG
    org.springframework.security: DEBUG
